# Stage 1: Build
FROM node:20.11.1-alpine AS builder

WORKDIR /usr/src/app

COPY ./client/package*.json ./

RUN npm install

COPY ./client .

RUN npm run build

FROM nginx:1.27.1-alpine

COPY --from=builder /usr/src/app/dist /usr/share/nginx/html

RUN rm /etc/nginx/conf.d/default.conf

COPY ../nginx/nginx.prod.conf /etc/nginx/nginx.conf

COPY --from=builder /usr/src/app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
