# Dockerfile.prod for client/frontend
FROM node:20.11.1-alpine AS builder

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM nginx:1.27.1
COPY --from=builder /usr/src/app/dist /usr/share/nginx/html

COPY ./nginx/default.conf /etc/nginx/nginx.conf

EXPOSE 80