# dev.Dockerfile for client/frontend
FROM node:20.11.1-alpine

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

COPY tsconfig.json vite.config.ts ./
COPY . .

CMD ["npm", "run", "dev", "--", "--host"]