# Dockerfile.prod for client/frontend
FROM node:20.11.1-alpine AS builder

WORKDIR /usr/src/app

COPY package*.json ./
RUN yarn install

COPY . .
RUN npm run build

FROM nginx:1.27.1-alpine

RUN rm /etc/nginx/conf.d/default.conf
COPY --from=builder /usr/src/app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]