# docker-compose.dev.yml
version: "3.8"
services:
  server:
    container_name: coding-app-server
    environment:
      - NODE_ENV=development
    build:
      context: ./server
      dockerfile: dev.Dockerfile
    ports:
      - "3333:3333"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - database-sql
    command: ["npx", "tsx", "watch", "src/index.ts"]
    expose:
      - "3333"

  database-sql:
    container_name: coding-app-postgresql-db
    image: postgres:16.4-bullseye
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - server/.env

  client:
    container_name: coding-app-client
    build:
      context: ./client
      dockerfile: dev.Dockerfile
    # ports:
    #   - "5173:5173"
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - server
    environment:
      - client/.env
    # command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    expose:
      - "5173"

  nginx:
    image: nginx:1.27.1
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
    container_name: reverse-proxy
    depends_on:
      - server
      - client

  # migrate:
  #   image: node:20.11.1-alpine
  #   volumes:
  #     - ./server:/usr/src/app
  #     - /usr/src/app/node_modules
  #   working_dir: /usr/src/app
  #   command: ["npm", "run", "db:migrate:script"]
  #   depends_on:
  #     - database-sql

  # playwright-e2e:
  #   entrypoint: "/bin/true"
  #   build:
  #     context: ./playwright-e2e
  #     dockerfile: dev.Dockerfile
  #   network_mode: host
  #   # depends_on:
  #   #   - ui
  #   volumes:
  #     - ./playwright-e2e/tests:/usr/src/app/tests

volumes:
  postgres_data:
