# docker-compose.test-ci.yml
services:
  server:
    container_name: coding-app-server
    image: ${SERVER_IMAGE}
    depends_on:
      - database-sql
    restart: unless-stopped
    environment:
      NODE_ENV: test
      TEST_DATABASE_URL: ${TEST_DATABASE_URL}
      SERVER_PORT: 3333
      SERVER_HOST: 0.0.0.0

  database-sql:
    container_name: coding-app-postgresql-db
    image: postgres:16.4-bullseye
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

  client:
    container_name: coding-app-client
    image: ${CLIENT_IMAGE}
    depends_on:
      - server
    environment:
      VITE_BASE_URL: /api1
    expose:
      - "80"

  nginx:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    container_name: reverse-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro

    depends_on:
      - server
      - client
    restart: unless-stopped

volumes:
  postgres_data:
