# docker-compose.test-ci.yml temp temp temp
services:
  server:
    container_name: coding-app-server
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    depends_on:
      - database-sql
    restart: unless-stopped
    environment:
      NODE_ENV: test
      DATABASE_URL: postgres://patrick:jlafei8910fQQ-Hw92.W1l@database-sql:5432/coding-app-db
      TEST_DATABASE_URL: postgres://patrick:jlafei8910fQQ-Hw92.W1l@database-sql:5432/coding-app-db-test
      SERVER_PORT: 3333
      SERVER_HOST: 0.0.0.0

  database-sql:
    container_name: coding-app-postgresql-db
    image: postgres:16.4-bullseye
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # env_file:
    # - temp

  migrate:
    container_name: coding-app-db-migrate
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    command: /bin/sh -c "npm run db:migrate:script:test && npm run db:migrate:script"
    depends_on:
      - database-sql
    environment:
      - NODE_ENV=test

  client:
    container_name: coding-app-client
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    depends_on:
      - server
    environment:
      VITE_BASE_URL: /api1

  nginx:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    container_name: reverse-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro

    depends_on:
      - server
      - client
    restart: unless-stopped

volumes:
  postgres_data:
