# docker-compose.dev.yml
version: "3.8"

services:
  server:
    container_name: coding-app-server
    environment:
      - NODE_ENV=development
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - database-sql
    command: ["npx", "tsx", "watch", "src/index.ts"]
    expose:
      - "3333"
    env_file:
      - server/.env.development

  database-sql:
    container_name: coding-app-postgresql-db
    image: postgres:16.4-bullseye
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - server/.env.development

  client:
    container_name: coding-app-client
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - server
    environment:
      - client/.env.development
    expose:
      - "5173"

  nginx:
    image: nginx:1.27.1
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
    container_name: reverse-proxy
    restart: always
    depends_on:
      - server
      - client

  # playwright-e2e:
  #   entrypoint: "/bin/true"
  #   build:
  #     context: ./playwright-e2e
  #     dockerfile: Dockerfile.dev
  #   network_mode: host
  #   # depends_on:
  #   #   - ui
  #   volumes:
  #     - ./playwright-e2e/tests:/usr/src/app/tests

volumes:
  postgres_data:
