# docker-compose.dev.yml
services:
  server:
    container_name: coding-app-server
    environment:
      NODE_ENV: development
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - migrate
      - database-sql
    command: ["npx", "tsx", "watch", "src/index.ts"]
    env_file:
      - server/.env.development

  database-sql:
    container_name: coding-app-postgresql-db
    image: postgres:16.4-bullseye
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - server/.env.development

  migrate:
    container_name: coding-app-db-migrate
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    command: npm run db:migrate:script
    depends_on:
      - database-sql
    environment:
      - NODE_ENV=dev
    env_file:
      - server/.env.development

  client:
    container_name: coding-app-client
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - server
    env_file:
      - client/.env.development

  nginx:
    image: nginx:1.27.1
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
    container_name: reverse-proxy
    restart: always
    depends_on:
      - server
      - client

volumes:
  postgres_data:
