# docker-compose.test-localyml
services:
  test-database-sql:
    container_name: coding-app-postgresql-test-db
    image: postgres:16.4-bullseye
    restart: always
    environment:
      POSTGRES_USER: patricktest
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: coding-app-db-test
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

volumes:
  postgres_test_data:
