# docker-compose.prod.yml
version: "3.8"

services:
  server:
    container_name: coding-app-server
    # environment:
    #   - NODE_ENV=production
    #   - PORT=3335
    env_file:
      - ./server/.env.production
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    depends_on:
      - database-sql
    restart: unless-stopped
    # expose:
    #   - "3335"

  database-sql:
    container_name: coding-app-postgresql-db
    image: postgres:16.4-bullseye
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - server/.env.production

  client:
    container_name: coding-app-client
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    depends_on:
      - server
    environment:
      - client/.env.production
    expose:
      - "80"

  nginx:
    build:
      context: ./client 
      dockerfile: Dockerfile.prod
    container_name: reverse-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro 
  
    depends_on:
      - server
      - client
    restart: unless-stopped

volumes:
  postgres_data:
