# docker-compose.prod.yml
services:
  server:
    container_name: coding-app-server
    image: patske3000/coding-app:server-529b4f2c7d2560faa8727dbb8fdb2deab25fb288
    depends_on:
      - database-sql
    restart: unless-stopped
    env_file:
      - server/.env.development
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://patrick:jlafei8910fQQ-Hw92.W1l@database-sql:5432/coding-app-db
      SERVER_PORT: 3333
      SERVER_HOST: 0.0.0.0

  database-sql:
    container_name: coding-app-postgresql-db
    image: postgres:16.4-bullseye
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data

  client:
    container_name: coding-app-client
    image: patske3000/coding-app:client-529b4f2c7d2560faa8727dbb8fdb2deab25fb288
    depends_on:
      - server
    environment:
      VITE_BASE_URL: /api1
    expose:
      - "80"

  nginx:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    container_name: reverse-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server
      - client
    restart: unless-stopped

volumes:
  postgres_data:
