version: "3.8"
services:
  server:
    environment:
      - NODE_ENV=development
    build:
      context: ./server
      dockerfile: dev.Dockerfile
    ports:
      - "3333:3333"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - database-sql
    command: ["npx", "tsx", "watch", "src/index.ts"]

  database-sql:
    container_name: postgresql_db_coding_app
    image: postgres:16.4-bullseye
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - server/.env

  playwright-e2e:
    entrypoint: "/bin/true"
    build:
      context: ./playwright-e2e
      dockerfile: dev.Dockerfile
    network_mode: host
    # depends_on:
    #   - ui
    volumes:
      - ./playwright-e2e/tests:/usr/src/app/tests

  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4
  #   ports:
  #     - "8080:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: "pgadmin@example.com"
  #     PGADMIN_DEFAULT_PASSWORD: "pgadmin"
  #   restart: unless-stopped

volumes:
  postgres_data:
