# docker-compose.prod.yml

services:
  server:
    container_name: coding-app-server
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    depends_on:
      - database-sql
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      SERVER_PORT: ${SERVER_PORT}
      SERVER_HOST: ${SERVER_HOST}

  database-sql:
    container_name: coding-app-postgresql-db
    image: postgres:16.4-bullseye
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data

  client:
    container_name: coding-app-client
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    depends_on:
      - server
    environment:
      VITE_BASE_URL: ${VITE_BASE_URL}
    expose:
      - "80"

  nginx:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    container_name: reverse-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro

    depends_on:
      - server
      - client
    restart: unless-stopped

volumes:
  postgres_data:
