# docker-compose.stag.yml
services:
  server:
    container_name: crm-app-server
    image: ${SERVER_IMAGE}
    restart: unless-stopped
    environment:
      NODE_ENV: production
      SERVER_PORT: ${SERVER_PORT}
      SERVER_HOST: ${SERVER_HOST}
      POSTGRES_DB: crm_app_db_stag
      DATABASE_URL: ${DATABASE_URL_STAG}

  frontend-proxy:
    image: ${FRONTEND_IMAGE}
    container_name: frontend-proxy
    ports:
      - "80:80"
    restart: unless-stopped
    # test push to feat/test-stag branch
    # toimiiko
    # test pr flow
    # build
