version: "3.8"

services:
  server:
    container_name: coding-app-server
    environment:
      - NODE_ENV=production
    env_file:
      - ./server/.env.prod
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    ports:
      - "3335:3335"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - database-sql
    restart: unless-stopped
    expose:
      - "3335"

  database-sql:
    container_name: coding-app-postgresql-db
    image: postgres:16.4-bullseye
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - server/.env.prod

  client:
    container_name: coding-app-client
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    ports:
      - "5173:5173"
    depends_on:
      - server
    environment:
      # - client/.env.production
      - VITE_API_URL=http://localhost:3335/api1 
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - ./client/dist:/usr/share/nginx/html:ro 
    expose:
      - "5173"

  nginx:
    image: nginx:1.27.1-alpine
    container_name: reverse-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - ./client/dist:/usr/share/nginx/html:ro 
    depends_on:
      - server
      - client
    restart: unless-stopped

volumes:
  postgres_data: