const mockCustomers = [
    {
      customer_id: "1",
      name: "John Doe",
      email: "johndoe@example.com",
      last_order: "2023-12-25",
      num_orders: 5,
      total_spent: 1200.50,
    },
    {
      customer_id: "2",
      name: "Jane Smith",
      email: "janesmith@example.com",
      last_order: "2023-11-10",
      num_orders: 2,
      total_spent: 450.75,
    },
    {
      customer_id: "3",
      name: "Michael Johnson",
      email: "michaelj@example.com",
      last_order: "2023-12-01",
      num_orders: 7,
      total_spent: 3200.00,
    },
    {
      customer_id: "4",
      name: "Emily Davis",
      email: "emilyd@example.com",
      last_order: "2023-10-15",
      num_orders: 3,
      total_spent: 675.00,
    },
    {
      customer_id: "5",
      name: "Chris Brown",
      email: "chrisb@example.com",
      last_order: "2023-12-20",
      num_orders: 8,
      total_spent: 2800.99,
    },
    {
      customer_id: "6",
      name: "Sarah Wilson",
      email: "sarahw@example.com",
      last_order: "2023-11-25",
      num_orders: 6,
      total_spent: 1500.40,
    },
    {
      customer_id: "7",
      name: "David Lee",
      email: "davidl@example.com",
      last_order: "2023-12-05",
      num_orders: 4,
      total_spent: 980.25,
    },
    {
      customer_id: "8",
      name: "Sophia Martinez",
      email: "sophiam@example.com",
      last_order: "2023-11-30",
      num_orders: 10,
      total_spent: 4000.00,
    },
    {
      customer_id: "9",
      name: "James Anderson",
      email: "jamesa@example.com",
      last_order: "2023-12-10",
      num_orders: 1,
      total_spent: 150.00,
    },
    {
      customer_id: "10",
      name: "Olivia White",
      email: "oliviaw@example.com",
      last_order: "2023-10-01",
      num_orders: 12,
      total_spent: 5500.75,
    },
  ];
  
  export default mockCustomers;