name: Unit and Integration Tests

on:
  push:
    branches:
      - main
      - "feature/*"
      - "fix/*"
    paths-ignore:
      - README.md
      - docs/**

  pull_request:
    branches: [main]
    types: [opened, synchronize]
    paths-ignore:
      - "README.md"
      - "docs/**"

jobs:
  client-unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ./client/node_modules
          key: ${{ runner.os }}-client-node-${{ hashFiles('client/package-lock.json') }}-${{ runner.os }}
          restore-keys: |
            ${{ runner.os }}-client-node-  

      - name: Install frontend dependencies
        run: npm install
        working-directory: ./client

      - name: Check style/lint
        run: npm run lint
        working-directory: ./client

      - name: Run TypeScript type checks
        run: npm run typecheck
        working-directory: ./client

      - name: Run npm audit
        run: npm audit --audit-level=high
        working-directory: ./client

      - name: Run frontend unit tests
        run: npm run test:unit:ci
        working-directory: ./client

      - name: Upload frontend coverage results
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: client-coverage
          path: client/coverage

  server-unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ./server/node_modules
          key: ${{ runner.os }}-server-node-${{ hashFiles('server/package-lock.json') }}-${{ runner.os }}
          restore-keys: |
            ${{ runner.os }}-server-node-
        continue-on-error: true

      - name: Remove node_modules
        run: rm -rf node_modules package-lock.json
        working-directory: ./server

      - name: Install server dependencies
        run: npm install
        working-directory: ./server

      - name: Run TypeScript type checks
        run: npm run tsc --noEmit
        working-directory: ./server

      - name: Run npm audit
        run: npm audit --audit-level=high
        working-directory: ./server

      - name: Run server unit tests
        run: npm run test:unit:ci
        working-directory: ./server

      - name: Upload server coverage results
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: server-coverage
          path: server/coverage

  integration-tests:
    needs: [client-unit-tests, server-unit-tests]
    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      NODE_ENV: test
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      TEST_DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_DB: coding-app-db-test
      SERVER_PORT: 3333
      SERVER_HOST: 0.0.0.0
      VITE_BASE_URL: /api1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Start Application with Docker Compose
        run: |
          docker-compose -f docker-compose.ci.yml up -d
          echo "Waiting for services to be ready..."
          until curl -s http://localhost:80/health; do
            echo "Waiting for backend to be ready..."
            sleep 8
          done
          echo "Services are ready!"

      - name: Wait for Postgres DB to be ready
        run: |
          until docker exec coding-app-postgresql-db pg_isready -U ${{ secrets.POSTGRES_USER }}; do
            echo "Waiting for Postgres to be ready..."
            sleep 8
          done
          echo "Postgres is ready!"
        continue-on-error: true

      - name: Create test database if it doesn't exist
        run: |
          echo "Creating test database if it doesn't exist..."
          docker exec coding-app-postgresql-db psql -U ${{ secrets.POSTGRES_USER }} -d postgres -c "DO \$\$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = 'coding-app-db-test') THEN EXECUTE 'CREATE DATABASE coding-app-db-test'; END IF; END \$\$;"
        continue-on-error: true

      - name: Run generate migration files TEST-DB
        run: |
          docker-compose -f docker-compose.ci.yml exec server npm run db:generate:test
        continue-on-error: true

      - name: Run drizzle kit migrations TEST-SB
        run: |
          docker-compose -f docker-compose.ci.yml exec server sh -c "NODE_ENV=test npx drizzle-kit generate"

        continue-on-error: true

      - name: Run migration script TEST-DB
        run: |
          docker-compose -f docker-compose.ci.yml exec server npm run db:migrate:script:test
        continue-on-error: true

      - name: Seed test data in the database
        run: |
          echo "Seeding data into test database..."
          docker exec coding-app-postgresql-db psql -U ${{ secrets.POSTGRES_USER }} -d coding-app-db-test -c "
          INSERT INTO test_items_two (id, content, important) VALUES
          ('1', 'Test Word 1', true),
          ('2', 'Test Word 2', false),
          ('3', 'Test Word 3', true);
          "
        continue-on-error: true

      # Debug
      - name: Check migration logs
        run: |
          echo "Checking migration logs..."
          docker logs coding-app-db-migrate
        continue-on-error: true

      # Debug
      - name: Check all databases for the user
        run: |
          echo "Listing all databases for user..."
          docker exec coding-app-postgresql-db psql -U ${{ secrets.POSTGRES_USER }} -d postgres -c "\l"
        continue-on-error: true

      # Debug
      - name: Check database tables
        run: |
          echo "Listing tables in the TEST database..."
          docker exec coding-app-postgresql-db psql -U ${{ secrets.POSTGRES_USER }} -d coding-app-db-test -c "\dt"
        continue-on-error: true

      # Debug
      - name: Check test data exists in table
        run: |
          echo "Listing all rows in the test_items_two table..."
          docker exec coding-app-postgresql-db psql -U ${{ secrets.POSTGRES_USER }} -d coding-app-db-test -c "SELECT * FROM test_items_two;"
        continue-on-error: true

      - name: Run Integration Tests
        run: |
          docker-compose -f docker-compose.ci.yml exec server npm run test:integration:ci

      - name: Upload Integration Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: integration-test-results
          path: ./integration-tests/results

      # e2e-tests:
      #   needs: [integration-tests]
      #   runs-on: ubuntu-latest
      #   timeout-minutes: 5

      #   steps:
      #     - name: Checkout code
      #       uses: actions/checkout@v4

      #     - name: Set up Node.js
      #       uses: actions/setup-node@v4
      #       with:
      #         node-version: "20"

      - name: Install Playwright dependencies
        run: npm install
        working-directory: ./playwright-e2e

      - name: Install Playwright Browsers
        # run: npx playwright install --with-deps
        run: yarn playwright install --with-deps
        working-directory: ./playwright-e2e
        continue-on-error: true

      - name: Run E2E tests
        run: npm run test:e2e
        continue-on-error: true

      - name: Upload E2E Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: ./playwright-e2e/playwright-report/
          retention-days: 30

      - name: Upload Screenshots as Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: e2e-screenshots
          path: ./screenshots/*.png

      - name: Stop and Remove Containers
        run: |
          docker-compose -f docker-compose.ci.yml down
