name: Build and Push Production Docker Images

on:
  workflow_run:
    workflows: ["Unit and Integration Tests"]
    types:
      - completed

jobs:
  build-application-and-images:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [client, server] #
    outputs:
      client_sha: ${{ steps.set_output_client.outputs.frontend-proxy_image_sha || '' }}
      server_image_sha: ${{ steps.set_output_server.outputs.server_image_sha || '' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ${{ matrix.app == 'client' && './client/node_modules' || './server/node_modules' }}
          key: ${{ runner.os }}-${{ matrix.app }}-node-${{ matrix.app == 'client' && hashFiles('client/package-lock.json') || hashFiles('server/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.app }}-node-

      - name: Build application
        run: npm run build
        working-directory: ${{ matrix.app == 'client' && './client' || './server' }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # aws
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Docker Hub and AWS ECR
      - name: Build and push to Docker Hub and AWS ECR
        id: build
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.app == 'client' && './client' || './server' }}
          file: ${{ matrix.app == 'client' && './client/Dockerfile.prod' || './server/Dockerfile.prod' }}
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/coding-app:${{ matrix.app }}-${{ github.sha }}
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.AWS_ECR_REPO_NAME }}:${{ matrix.app }}-${{ github.sha }}
          platforms: linux/amd64
